version: '3'
services:
  build:
    build: ./docker-images/my-angular-image
    container_name: angular-setup
    command: > 
      /bin/bash -c "
      echo start create new app &&
      if [ ${SKIP_GENERATE_APP} = false ];then ng new ${ANGULAR_APP_NAME} --routing true --skip-git --style scss;fi &&
      echo install pacakges &&
      cd ${ANGULAR_APP_NAME} && 
      ng add @angular-eslint/schematics --skip-confirmation &&
      npm install --save-dev eslint-config-prettier &&
      npm install &&
      exit
      "
    environment:
      - NG_CLI_ANALYTICS=false
    volumes:
      - ./angular:/project
    working_dir: /project

  devenv:
    tty: true
    container_name: angular
    build:  ./docker-images/my-angular-image
    depends_on:
      build:
        condition: service_completed_successfully 
    command: > 
      /bin/bash -c "
      npm install &&
      ng s --host 0.0.0.0
      "
    environment:
      - NG_CLI_ANALYTICS=false
    ports:
      - "4200:4200"
    volumes:
      - ./angular/${ANGULAR_APP_NAME}:/project/
      - /project/node_modules
    working_dir: /project

  sample-api:
    build: ./docker-images/sample-api
    container_name: sample-api
    depends_on:
      build:
        condition: service_completed_successfully
    command: > 
      /bin/bash -c "
      json-server --watch db.json --port 3000 -H 0.0.0.0
      "
    ports:
      - "3000:3000"
    volumes:
      - ./docker-images/sample-api/data:/data
    working_dir: /data